<div class="col-lg-6 wow fadeIn" data-wow-delay=".2s">
    <h2 class="section__title">Faça uma proposta</h2>
    <p class="section__text">Preencha o formulário a seguir com sua proposta e logo nosso representante irá entrar em contato.</p>

    <form class="form" action="" method="post" id="formProposta">
        <div class="form__control">
            <input type="text" name="newsletter_nome" class="form__input" placeholder="Nome" required>
        </div>
        <div class="form__control">
            <input type="email" name="newsletter_email" class="form__input" placeholder="E-mail" required>
        </div>
        <div class="form__control">
            <input type="tel" name="newsletter_telefone" class="form__input js-phone" placeholder="Telefone" required>
        </div>
        <div class="form__control">
            <textarea class="form__input" name="mensagem" placeholder="Mensagem" required></textarea>
        </div>
        <div class="form__footer">
            <div class="checkbox">
                <input id="newsletter" name="newsletter" type="checkbox" class="form__checkbox"/>
                <label for="newsletter">Assine nossa newsletter</label>
            </div>

            <button class="button button--orange" type="submit">Enviar</button>
        </div>
    </form>

    <div class="vehicle__contact">
        <p class="vehicle__text">Se preferir ligue:</p>
        <ul class="vehicle__list">
            <li>
                <a href="tel:1120959595" target="_blank"><img src="<?=$URLSITE?>/page/assets/img/tel.jpg" alt="Telefone"></a>
                <a href="tel:1120959595" target="_blank"><p>11 2095-9595</p></a>
            </li>
            <li>
               <a href="https://api.whatsapp.com/send?phone=5511989402988" target="_blank"> <img src="<?=$URLSITE?>/page/assets/img/zap.jpg" alt="WhatsApp"></a>
               <a href="https://api.whatsapp.com/send?phone=5511989402988" target="_blank"><p>11 98940-2988</p></a>
            </li>
        </ul>
    </div>
    <div class="vehicle__contact">
        <p class="vehicle__text">Compartilhe com os amigos:</p>
        <ul class="vehicle__list">
            <li><a href="https://twitter.com/comfortcar" rel="noopener" target="_blank"><img src="<?=$URLSITE?>/page/assets/img/twitter.jpg" alt="Compartilhar no Twitter"></a></li>
            <li><a href="https://www.facebook.com/Comfortcar" rel="noopener" target="_blank"><img src="<?=$URLSITE?>/page/assets/img/like.jpg" alt="Like no Facebook"></a></li>
        </ul>
    </div>
</div>
</div>